package shared;

public enum MessageType {
    LOGIN, REGISTER,
    CONTACT_MOD, MOD_RESPONSE, APPROVE_MOD,
    CREATE_ROOM, INVITE_SELLER, SELLER_CONFIRM, APPROVE_PRODUCT, REJECT_PRODUCT,
    OPEN_AUCTION, NEXT_PRODUCT, EXTEND_TIME, CLOSE_ROOM,
    GET_SELLER_PRODUCTS,
    JOIN_ROOM, LEAVE_ROOM, PLACE_BID,
    BID_UPDATE, AUCTION_END, ROOM_STATUS_UPDATE, PRODUCT_CHANGE,
    CHAT_ROOM, CHAT_PRIVATE,
    ERROR, SUCCESS, HEARTBEAT, KICK_USER, LIST_ROOMS, ROOM_INFO,
    GET_HISTORY, GET_MOD_LIST, GET_ROOM_LIST,
    GET_ROOM_DETAIL, GET_ADMIN_STATS, GET_PENALTY_LIST,
    CONFIRM_BUY, EXPORT_HISTORY, MARK_TRANSACTION_COMPLETED,
    // Notification system
    NOTIFICATION, GET_NOTIFICATIONS, MARK_NOTIFICATION_READ,
    // Room creation with sellers
    CREATE_ROOM_WITH_SELLERS, ADD_SELLER_TO_ROOM, REMOVE_SELLER_FROM_ROOM,
    GET_USER_LIST,
    // Moderator: Add product to active room
    ADD_PRODUCT_TO_ROOM,
    // Product management
    SUBMIT_PRODUCT, GET_MY_PRODUCTS, GET_PENDING_PRODUCTS, GET_ALL_PRODUCTS,
    GET_APPROVED_PRODUCTS_IN_ROOM, ADD_PRODUCT_TO_SESSION, ROOM_PRODUCT_LIST_UPDATE,
    // Transactions
    GET_SUCCESSFUL_TRANSACTIONS,
    // Rating
    RATE_USER, GET_RATINGS,
    // Resale
    REQUEST_RESALE
}
