package shared;

public enum MessageType {
    LOGIN, REGISTER,
    CONTACT_MOD, MOD_RESPONSE,
    CREATE_ROOM, INVITE_SELLER, SELLER_CONFIRM, APPROVE_PRODUCT, REJECT_PRODUCT,
    OPEN_AUCTION, NEXT_PRODUCT, EXTEND_TIME, CLOSE_ROOM,
    JOIN_ROOM, LEAVE_ROOM, PLACE_BID,
    BID_UPDATE, AUCTION_END, ROOM_STATUS_UPDATE, PRODUCT_CHANGE,
    CHAT_ROOM, CHAT_PRIVATE,
    ERROR, SUCCESS, HEARTBEAT, KICK_USER, LIST_ROOMS, ROOM_INFO,
    GET_HISTORY, GET_MOD_LIST, GET_ROOM_LIST,
    GET_ROOM_DETAIL, GET_ADMIN_STATS, GET_PENALTY_LIST,
    CONFIRM_BUY, EXPORT_HISTORY,
    // Notification system
    NOTIFICATION, GET_NOTIFICATIONS, MARK_NOTIFICATION_READ,
    // Room creation with sellers
    CREATE_ROOM_WITH_SELLERS, ADD_SELLER_TO_ROOM, REMOVE_SELLER_FROM_ROOM,
    GET_USER_LIST
}
